apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: other-resources
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: tools
  source:
    path: apps/other-resources
    repoURL: https://github.com/alterus-io/k8s-tools-app.git
    targetRevision: master
    helm:
      values: |
        argoHost: "argo.demo.alterus.io"
        issuerEmail: "adam@alterus.io"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true